ARG NODE_ENV=production
ARG FORCE_SSL=true

# ----------------------------------------------------------------
FROM node:iron-alpine as build_frontend
ARG NODE_ENV
ARG FORCE_SSL
ENV NODE_ENV $NODE_ENV
RUN adduser -D outpost-user

RUN apk update
RUN apk add curl

COPY ./package.json ./tmp/package.json
COPY ./package-lock.json ./tmp/package-lock.json

WORKDIR /tmp

RUN if [ "${NODE_ENV}" = "development" ] || [ -z "${NODE_ENV}" ]; then \
    npm install; fi
RUN if [ "${NODE_ENV}" = "production" ]; then \
    npm ci --omit=dev && npm cache clean --force; fi

USER outpost-user
WORKDIR /app

# ----------------------------------------------------------------
FROM build_frontend
ARG NODE_ENV
ARG FORCE_SSL
ENV NODE_ENV $NODE_ENV
ENV FORCE_SSL $FORCE_SSL

COPY --from=build_frontend --chown=outpost-user:outpost-user /tmp/node_modules /app/node_modules
COPY --chown=outpost-user:outpost-user . /app

USER outpost-user
EXPOSE 3000
ENTRYPOINT ["npm", "run"]
CMD ["start"]
