version: "3.7"
services:
  outpost-api:
    stdin_open: true
    image: "outpost-api:development"
    container_name: outpost-api-dev
    depends_on:
      - mongo
    build:
      target: development
    ports:
      - "3001"
    volumes:
      - ./:/app:cached
    environment:
      NODE_ENV: development
      DB_URI: mongodb://mongo:27017/outpost_api_development
    networks:
      - external_network
      - internal_network
  mongo:
    image: mongo:6
    container_name: outpost-api-mongo
    ports:
      - 27017:27017
    volumes:
      - outpost-api-mongo-volume:/data/db
    networks:
      - internal_network
      - external_network

volumes:
  outpost-api-mongo-volume:

networks:
  external_network:
  internal_network:
    internal: true
