version: "3.7"
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - internal_network

volumes:
  redis:
    driver: local
